services:
  - type: web
    name: whatsapp-gemini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash-lite
      - key: LANGUAGE_CODE
        value: de
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: WC_CONSUMER_KEY
        sync: false
      - key: WC_CONSUMER_SECRET
        sync: false
      - key: WC_STORE_URL
        value: https://durmusbaba.de 